### ISSUE TITLE
Still Developing?

### ISSUE THREAD

**Issue by Mortal-Engine** [curiores/SerialAnalyzer#5]
Greetings, I was watching your youtube channel and was quite impressed with the work! Are you still working on arduino projects? Would like to have a chat with you sometime. Thanks in advance!

**Comment by curiores** [comment]
Yes, I am still working on Arduino projects. Been a bit busy lately, so
haven't yet completed a new video.

Please feel free to email me at curiores@gmail.com

Best,
CR
