### ISSUE TITLE
Port access denied

### ISSUE THREAD

**Issue by wagmaz** [curiores/SerialAnalyzer#6]
I try to connect to my arduino UNO, but show this message: "Error starting serial port on Arduino Uno (COM4) Error: Opening COM4:  Access denied"

**Comment by curiores** [comment]
This usually happens if the port is already in use, for example, by the Arduino app.

It's unlikely this is a bug in the app itself. Windows needs to unlock the port before the app is able to access it. If the port is locked or blocked by the OS, the app won't be able to access it.

**Comment by wagmaz** [comment]
Tks a lot, I just close the arduino app and it work. tks
________________________________
De: curiores ***@***.***>
Enviado: sábado, 17 de junho de 2023 18:20
Para: curiores/SerialAnalyzer ***@***.***>
Cc: wagmaz ***@***.***>; Author ***@***.***>
Assunto: Re: [curiores/SerialAnalyzer] Port access denied (Issue #6)


This usually happens if the port is already in use, for example, by the Arduino app.

It's unlikely this is a bug in the app itself. Windows needs to unlock the port before the app is able to access it. If the port is locked or blocked by the OS, the app won't be able to access it.

**Comment by curiores** [comment]
No problem 😉
