### ISSUE TITLE
Unable to copy Serial Monitor data 

### ISSUE THREAD

**Issue by reganxavier-hub** [curiores/SerialAnalyzer#7]
Please provide an update by modifying the ware such that it would be viable to copy the data from serial monitor

**Comment by curiores** [comment]
A sensible enhancement. I'll consider adding this when I have some time.

**Comment by reganxavier-hub** [comment]
Great

**Comment by reganxavier-hub** [comment]
Please post an update once you done it

**Comment by reganxavier-hub** [comment]
Waiting for update

**Comment by curiores** [comment]
Updated V1.1.0 to stream serial data to text file via "record" functionality
